openapi: 3.0.1
info:
  title: meli-bff
  description: BFF en NodeJS para Test de MercadoLibre
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Items
    description: MercadoLibre example endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /items:
    post:
      tags:
        - Items
      description: Query for results
      parameters:
        - name: q
          in: query
          description: The search keyword
          required: true
          schema:
            type: string
      requestBody:
        description: author of the request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '200':
          description: Returns all results
        '404':
          description: No results found
        '401':
          description: Unauthorized
  /items/{id}:
    post:
      tags:
        - Items
      parameters:
        - name: id
          in: path
          description: The id of the item to retrieve
          required: true
          schema:
            type: string
      requestBody:
        description: author of the request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '200':
          description: Return the item with the specified id
        '204':
          description: Item not found
        '401':
          description: Unauthorized
  /spec:
    get:
      tags:
        - Specification
      responses:
        '200':
          description: Return the API specification
components:
  schemas:
    Author:
      type: object
      properties:
        author:
          type: object
          properties:
            name:
              type: string
            lastName:
              type: string
          example:
            name: Lautaro
            lastName: Tejerina
          required:
            - name
            - lastName
  requestBodies:
    AuthBody:
      description: author of the request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Author'
